# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.cache/wt [current_project]
set_property parent.project_path C:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.xpr [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog C:/Users/lingz/Desktop/Verilog/termist/src/common.vh
read_verilog -library xil_defaultlib {
  C:/Users/lingz/Desktop/Verilog/termist/src/alu.v
  C:/Users/lingz/Desktop/Verilog/termist/src/axi_drive.v
  C:/Users/lingz/Desktop/Verilog/termist/src/brcond.v
  C:/Users/lingz/Desktop/Verilog/termist/src/cache.v
  C:/Users/lingz/Desktop/Verilog/termist/src/control.v
  C:/Users/lingz/Desktop/Verilog/termist/src/datapath.v
  C:/Users/lingz/Desktop/Verilog/termist/src/immgen.v
  C:/Users/lingz/Desktop/Verilog/termist/src/mips.v
  C:/Users/lingz/Desktop/Verilog/termist/src/regfile.v
  C:/Users/lingz/Desktop/Verilog/termist/src/soc.v
}
read_ip -quiet c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_sys2ddr3/clk_sys2ddr3.xci
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_sys2ddr3/clk_sys2ddr3_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_sys2ddr3/clk_sys2ddr3.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_sys2ddr3/clk_sys2ddr3_ooc.xdc]

read_ip -quiet c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user.xci
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user_ooc.xdc]

read_ip -quiet c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/mig_7series_0_1/mig_7series_0.xci
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/mig_7series_0_1/mig_7series_0/user_design/constraints/mig_7series_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/mig_7series_0_1/mig_7series_0/user_design/constraints/mig_7series_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/constrs_1/new/soc_constraints.xdc
set_property used_in_implementation false [get_files C:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/constrs_1/new/soc_constraints.xdc]


synth_design -top soc -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef soc.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file soc_utilization_synth.rpt -pb soc_utilization_synth.pb"
