# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user.xci
# IP: The module: 'clk_ddr32user' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ddr32user'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ddr32user'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ddr32user'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user.xci
# IP: The module: 'clk_ddr32user' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ddr32user'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ddr32user'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: c:/Users/lingz/Desktop/Verilog/termist/vivado/project_mips.srcs/sources_1/ip/clk_ddr32user/clk_ddr32user_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_ddr32user'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
